### ISSUE TITLE
running with execption

### ISSUE THREAD

**Issue by tianwaideren** [quantifind/KafkaOffsetMonitor#102]
Exception in thread "main" com.quantifind.sumac.ArgException: expecting argument name beginning with "--", instead got 　--zk
        at com.quantifind.sumac.ArgumentParser$.parse$1(ArgumentParser.scala:59)
        at com.quantifind.sumac.ArgumentParser$.argListToKvMap(ArgumentParser.scala:67)
        at com.quantifind.sumac.Args$class.parse(Args.scala:34)
        at com.quantifind.kafka.offsetapp.OffsetGetterArgs.parse(OffsetGetterApp.scala:18)
        at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:38)
        at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:38)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb.main(OffsetGetterWeb.scala)

**Comment by tianwaideren** [comment]
I made it, it's my fault. scripts of start-up is wrong
