### ISSUE TITLE
When Start got error 

### ISSUE THREAD

**Issue by micky-zh** [quantifind/KafkaOffsetMonitor#110]
I trying to start a app as a demo ，fellow tutorial running command with 

`java -cp KafkaOffsetMonitor-assembly-0.2.1.jar \
     com.quantifind.kafka.offsetapp.OffsetGetterWeb \
     --offsetStorage kafka
     --zk test.a.server:8000,test.b.server:8000 \
     --port 8080 \
     --refresh 10.seconds \
     --retain 2.days`

but got error message. seems config error ,

Exception in thread "main" com.quantifind.sumac.ArgException: unknown option offsetStorage
usage: 
--retain	class scala.concurrent.duration.FiniteDuration	null
--refresh	class scala.concurrent.duration.FiniteDuration	null
--dbName	class java.lang.String	offsetapp
--port	int	14650
--zk	class java.lang.String	null
--zkSessionTimeout	class scala.concurrent.duration.Duration	30 seconds
--zkConnectionTimeout	class scala.concurrent.duration.Duration	30 seconds

	at com.quantifind.sumac.ArgumentParser$$anonfun$nameToHolder$2.apply(ArgumentParser.scala:10)
	at com.quantifind.sumac.ArgumentParser$$anonfun$nameToHolder$2.apply(ArgumentParser.scala:9)
	at scala.collection.Map$WithDefault.default(Map.scala:52)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at com.quantifind.sumac.ArgumentParser$$anonfun$parse$1.applyOrElse(ArgumentParser.scala:23)
	at com.quantifind.sumac.ArgumentParser$$anonfun$parse$1.applyOrElse(ArgumentParser.scala:21)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at scala.collection.TraversableLike$$anonfun$collect$1.apply(TraversableLike.scala:278)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:105)
	at com.quantifind.sumac.ArgumentParser.parse(ArgumentParser.scala:21)
	at com.quantifind.sumac.Args$class.parse(Args.scala:39)
	at com.quantifind.kafka.offsetapp.OffsetGetterArgs.parse(OffsetGetterApp.scala:29)
	at com.quantifind.sumac.Args$class.parse(Args.scala:34)
	at com.quantifind.kafka.offsetapp.OffsetGetterArgs.parse(OffsetGetterApp.scala:29)
	at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:39)
	at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:43)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb.main(OffsetGetterWeb.scala)

**Comment by k1ng87** [comment]
have to rebuild the jar file from source....jar file on download is an older release...

**Comment by micky-zh** [comment]
@k1ng87 thx；
