### ISSUE TITLE
start failure and when i access to 8080 port, only find empty pages, and the start choice "--offsetStorage kafka"  is no effective

### ISSUE THREAD

**Issue by zhangpfly** [quantifind/KafkaOffsetMonitor#122]
my start scripts
```
# java -cp KafkaOffsetMonitor-assembly-0.2.1.jar com.quantifind.kafka.offsetapp.OffsetGetterWeb \
> --zk 192.168.92.13:2181,192.168.92.14:2181,192.168.92.15:2181 \
> --port 8080 \
> --refresh 10.seconds \
> --retain 2.days
serving resources from: jar:file:/root/KafkaOffsetMonitor-assembly-0.2.1.jar!/offsetapp
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
log4j:WARN No appenders could be found for logger (org.I0Itec.zkclient.ZkConnection).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2018-01-19 14:21:09.754:INFO:oejs.Server:jetty-7.x.y-SNAPSHOT
2018-01-19 14:21:09.813:INFO:oejsh.ContextHandler:started o.e.j.s.ServletContextHandler{/,jar:file:/root/KafkaOffsetMonitor-assembly-0.2.1.jar!/offsetapp}
2018-01-19 14:21:09.847:INFO:oejs.AbstractConnector:Started SocketConnector@0.0.0.0:8080
^C2018-01-19 14:25:02.076:INFO:oejsh.ContextHandler:stopped o.e.j.s.ServletContextHandler{/,jar:file:/root/KafkaOffsetMonitor-assembly-0.2.1.jar!/offsetapp}
2018-01-19 14:25:02.177:WARN:oejut.QueuedThreadPool:1 threads could not be stopped
2018-01-19 14:25:02.177:INFO:oejut.QueuedThreadPool:Couldn't stop Thread[qtp910599202-15,5,main]
2018-01-19 14:25:02.188:INFO:oejut.QueuedThreadPool: at java.net.SocketInputStream.socketRead0(Native Method)
2018-01-19 14:25:02.188:INFO:oejut.QueuedThreadPool: at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
2018-01-19 14:25:02.188:INFO:oejut.QueuedThreadPool: at java.net.SocketInputStream.read(SocketInputStream.java:170)
2018-01-19 14:25:02.189:INFO:oejut.QueuedThreadPool: at java.net.SocketInputStream.read(SocketInputStream.java:141)
2018-01-19 14:25:02.190:INFO:oejut.QueuedThreadPool: at java.net.SocketInputStream.read(SocketInputStream.java:223)
2018-01-19 14:25:02.190:INFO:oejut.QueuedThreadPool: at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:301)
2018-01-19 14:25:02.190:INFO:oejut.QueuedThreadPool: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
2018-01-19 14:25:02.190:INFO:oejut.QueuedThreadPool: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
2018-01-19 14:25:02.190:INFO:oejut.QueuedThreadPool: at java.lang.Thread.run(Thread.java:745)
```
![image](https://user-images.githubusercontent.com/17722518/35137552-f464a3e8-fd24-11e7-9d01-8b706123fb3c.png)
----------------------
and the start choice "--offsetStorage kafka"  is no effective
![image](https://user-images.githubusercontent.com/17722518/35137620-3b1fbc5a-fd25-11e7-9605-4b005cc658a8.png)
my java version is 
```
# java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
kafka version : kafka_2.11-1.0.0
zookeeper : zookeeper-3.4.10

**Comment by chenlushun** [comment]
me too

**Comment by wuhulala** [comment]
@chenlushun @zhangpfly  This repo is defunct. Use this repo instead: https://github.com/Morningstar/kafka-offset-monitor

You can then grab the latest compiled release and use that.

**Comment by chenlushun** [comment]
@wuhulala    ok, thanks.
