### ISSUE TITLE
Ossfet monitor quietly stopped acquiring history

### ISSUE THREAD

**Issue by bjtieman** [quantifind/KafkaOffsetMonitor#39]
This looks like it might be somewhat related to [1]?? but we don't see any SQL exceptions in our logs.  What we do see is [2] after which the history stops being updated.

The rest of the WebUI continued to work as expect, the process just stopped acquiring new history.  All previous history before the stall was still viewable and accurate.

[1]
https://github.com/quantifind/KafkaOffsetMonitor/pull/28
[2]
2014-12-18 15:48:01.388:INFO:oejsh.ContextHandler:started o.e.j.s.ServletContextHandler{/,jar:file:/opt/kafka-offset-monitor/KafkaOffsetMonitor-assembly-0.2.0.jar!/offsetapp}
2014-12-18 15:48:01.406:INFO:oejs.AbstractConnector:Started SocketConnector@0.0.0.0:8080
Exception in thread "Timer-0" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.getGroups(OffsetGetterWeb.scala:98)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.writeToDb(OffsetGetterWeb.scala:44)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$2.run(OffsetGetterWeb.scala:56)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2014-12-18 16:04:24.882:WARN:oejs.ServletHandler:/group/<blah>
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.getInfo(OffsetGetterWeb.scala:94)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$1$$anonfun$intent$1.applyOrElse(OffsetGetterWeb.scala:142)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$1$$anonfun$intent$1.applyOrElse(OffsetGetterWeb.scala:138)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214)
        at unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:67)
        at unfiltered.response.Pass$PassingAttempt$class.attempt(pass.scala:60)
        at unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:62)
        at unfiltered.response.Pass$$anonfun$fold$1.apply(pass.scala:43)
        at unfiltered.response.Pass$FunctionAttempt.apply(pass.scala:72)
        at unfiltered.filter.Plan$class.doFilter(plans.scala:50)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$1.doFilter(OffsetGetterWeb.scala:133)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
        at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:910)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
        at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
        at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:744)

**Comment by Mortimerp9** [comment]
my theory is that the timer running the DB update goes stale after one of its tasks fail. See https://github.com/quantifind/KafkaOffsetMonitor/blob/master/src/main/scala/com/quantifind/kafka/offsetapp/OffsetGetterWeb.scala#L70

**Comment by Mortimerp9** [comment]
yes, that would be related to #28, I'll make a new release including this PR

**Comment by bjtieman** [comment]
Thanks!  Appreciate it :)
