### ISSUE TITLE
how package it

### ISSUE THREAD

**Issue by WeiEast** [quantifind/KafkaOffsetMonitor#44]
I hava change it , I want to know how to package

**Comment by mfirry** [comment]
You need to use [sbt](http://www.scala-sbt.org)
You can then package by running `sbt package`

**Comment by WeiEast** [comment]
I packaged it, but I run it 
Exception in thread "main" java.lang.NoClassDefFoundError: com/quantifind/sumac/Args
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getMethod0(Class.java:2856)
	at java.lang.Class.getMethod(Class.java:1668)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: com.quantifind.sumac.Args
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)

**Comment by Mortimerp9** [comment]
If you just want to test, then you can do something like:
`sbt 'run-main com.quantifind.kafka.offsetapp.OffsetGetterWeb'`

with the appropriate arguments.

To get a one jar with all the dependencies, run:
`sbt assembly`
instead of `package`.
