### ISSUE TITLE
cannot connect to zk server

### ISSUE THREAD

**Issue by lephix** [quantifind/KafkaOffsetMonitor#72]
I use following command to run monitor. I ran zookeeper, kafka, kafka-monitor in the same machine. Kafka is working good.

    java -cp KafkaOffsetMonitor-assembly-0.2.1.jar com.quantifind.kafka.offsetapp.OffsetGetterWeb --zk 127.0.0.1:2181 --port 8080 --refresh 10.seconds --retain 2.days
tain 2.days

But I get timeout error from the console like following.

    Exception in thread "Timer-0" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.getGroups(OffsetGetterWeb.scala:98)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.writeToDb(OffsetGetterWeb.scala:44)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$2.run(OffsetGetterWeb.scala:56)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
    2015-11-15 19:49:50.737:WARN:oejs.ServletHandler:/group
    org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.getGroups(OffsetGetterWeb.scala:98)

**Comment by lephix** [comment]
There is a network problem during my test.
