### ISSUE TITLE
Exception in offset parsing

### ISSUE THREAD

**Issue by lokeshhctm** [quantifind/KafkaOffsetMonitor#77]
Caused by: java.lang.NumberFormatException: For input string: "2623027956"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.parseInt(Integer.java:615)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at kafka.utils.Json$$anonfun$1.apply(Json.scala:27)
        at kafka.utils.Json$$anonfun$1.apply(Json.scala:27)
        at scala.util.parsing.json.Parser$$anonfun$number$1.applyOrElse(Parser.scala:140)
        at scala.util.parsing.json.Parser$$anonfun$number$1.applyOrElse(Parser.scala:140)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at scala.util.parsing.combinator.Parsers$$anonfun$acceptMatch$1.apply(Parsers.scala:627)
        at scala.util.parsing.combinator.Parsers$$anonfun$acceptMatch$1.apply(Parsers.scala:625)
        at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Failure.append(Parsers.scala:202)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)

**Comment by CrazyIvan007** [comment]
I have the same problem and i found, that the problem is in the JSON Helper from Kafka, where the NumberGenerator for the JSON Numbers convert the string .toInt instead of a long. 
I'm not to familiar with scala, but maybe just double the kafka function into the KafkaOffsetMonitor Namespace and set the NumberGenerator to .toLong

**Comment by lokeshhctm** [comment]
I have fixed the issue.
Can somebody please merge the file i have attached?
[StormOffsetGetter.scala.zip](https://github.com/quantifind/KafkaOffsetMonitor/files/138919/StormOffsetGetter.scala.zip)
