### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by shijinkui** [quantifind/KafkaOffsetMonitor#87]
the doc run command can't run.

```
java -cp KafkaOffsetMonitor-assembly-0.2.1.jar \
     com.quantifind.kafka.offsetapp.OffsetGetterWeb \
     --offsetStorage kafka
     --zk zk-server1,zk-server2 \
     --port 8080 \
     --refresh 10.seconds \
     --retain 2.days
```

Exception in thread "main" com.quantifind.sumac.ArgException: unknown option offsetStorage
usage:
--retain    class scala.concurrent.duration.FiniteDuration  null
--refresh   class scala.concurrent.duration.FiniteDuration  null
--dbName    class java.lang.String  offsetapp
--port  int 63870
--zk    class java.lang.String  null
--zkSessionTimeout  class scala.concurrent.duration.Duration    30 seconds
--zkConnectionTimeout   class scala.concurrent.duration.Duration    30 seconds

```
at com.quantifind.sumac.ArgumentParser$$anonfun$nameToHolder$2.apply(ArgumentParser.scala:10)
at com.quantifind.sumac.ArgumentParser$$anonfun$nameToHolder$2.apply(ArgumentParser.scala:9)
at scala.collection.Map$WithDefault.default(Map.scala:52)
at scala.collection.MapLike$class.apply(MapLike.scala:141)
at scala.collection.AbstractMap.apply(Map.scala:58)
at com.quantifind.sumac.ArgumentParser$$anonfun$parse$1.applyOrElse(ArgumentParser.scala:23)
at com.quantifind.sumac.ArgumentParser$$anonfun$parse$1.applyOrElse(ArgumentParser.scala:21)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
at scala.collection.TraversableLike$$anonfun$collect$1.apply(TraversableLike.scala:278)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
at scala.collection.TraversableLike$class.collect(TraversableLike.scala:278)
at scala.collection.AbstractTraversable.collect(Traversable.scala:105)
at com.quantifind.sumac.ArgumentParser.parse(ArgumentParser.scala:21)
at com.quantifind.sumac.Args$class.parse(Args.scala:39)
at com.quantifind.kafka.offsetapp.OffsetGetterArgs.parse(OffsetGetterApp.scala:29)
at com.quantifind.sumac.Args$class.parse(Args.scala:34)
```

**Comment by bluesky8640** [comment]
You can take a look at my issue: https://github.com/quantifind/KafkaOffsetMonitor/issues/86.

Thanks,
Jin
