### ISSUE TITLE
OffsetStorage  Issue

### ISSUE THREAD

**Issue by Micheal-Bigmac** [quantifind/KafkaOffsetMonitor#97]
I read the Document about KafkaOffsetMonitor ,I find some error about OffsetStorage . The Command is bellow :
java -cp KafkaOffsetMonitor-assembly-0.2.1.jar \
     com.quantifind.kafka.offsetapp.OffsetGetterWeb \
     --offsetStorage kafka
     --zk zk-server1,zk-server2 \
     --port 8080 \
     --refresh 10.seconds \
     --retain 2.days
The Error is bellow :
[root@hadoop2-master opt]# java -cp KafkaOffsetMonitor-assembly-0.2.1.jar \
>      com.quantifind.kafka.offsetapp.OffsetGetterWeb \
>      --offsetStorage storm
Exception in thread "main" com.quantifind.sumac.ArgException: unknown option offsetStorage
usage: 
--retain	class scala.concurrent.duration.FiniteDuration	null
--refresh	class scala.concurrent.duration.FiniteDuration	null
--dbName	class java.lang.String	offsetapp
--port	int	37396
--zk	class java.lang.String	null
--zkSessionTimeout	class scala.concurrent.duration.Duration	30 seconds
--zkConnectionTimeout	class scala.concurrent.duration.Duration	30 seconds

	at com.quantifind.sumac.ArgumentParser$$anonfun$nameToHolder$2.apply(ArgumentParser.scala:10)
	at com.quantifind.sumac.ArgumentParser$$anonfun$nameToHolder$2.apply(ArgumentParser.scala:9)
	at scala.collection.Map$WithDefault.default(Map.scala:52)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at com.quantifind.sumac.ArgumentParser$$anonfun$parse$1.applyOrElse(ArgumentParser.scala:23)
	at com.quantifind.sumac.ArgumentParser$$anonfun$parse$1.applyOrElse(ArgumentParser.scala:21)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at scala.collection.TraversableLike$$anonfun$collect$1.apply(TraversableLike.scala:278)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:105)
	at com.quantifind.sumac.ArgumentParser.parse(ArgumentParser.scala:21)
	at com.quantifind.sumac.Args$class.parse(Args.scala:39)
	at com.quantifind.kafka.offsetapp.OffsetGetterArgs.parse(OffsetGetterApp.scala:29)
	at com.quantifind.sumac.Args$class.parse(Args.scala:34)
	at com.quantifind.kafka.offsetapp.OffsetGetterArgs.parse(OffsetGetterApp.scala:29)
	at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:39)

==================================================================
The Command is using for read data from storm kafka spout

**Comment by Micheal-Bigmac** [comment]
I look at the some other issue  and  found this problem needs to be recompiled 
I tried to recompiled but  cannot  connect to com.twitter#util-core:3.0.0  
Could you rebuilt one and publish newer ? thanks  I am in China

**Comment by dannyruchman** [comment]
Hi,
I am trying to use it and get the same issue as above. Any chance to get a new build that overcomes this?

**Comment by taohorse** [comment]
i also get the same issue as above.

**Comment by rcasey212** [comment]
@Micheal-Bigmac @dannyruchman @taohorse For a temporary solution, try changing the reference in Build.scala to "util-core_2.10" and try recompiling.

**Comment by taohorse** [comment]
now i compiled success，here is a attachment.can monitor kafka success.








At 2017-01-12 01:47:07, "Robert Casey" <notifications@github.com> wrote:


@Micheal-Bigmac@dannyruchman@taohorse For a temporary solution, try changing the reference in Build.scala to "util-core_2.10" and try recompiling.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易126邮箱发来的云附件
KafkaOffsetMonitor-assembly-0.3.0-SNAPSHOT.jar (45.92M, 2017年2月5日 16:49 到期)
下载
QQ20170121-0@2x.png (177.07K, 2017年2月5日 16:51 到期)
在线预览 | 下载

**Comment by rcasey212** [comment]
@taohorse I don't see an attachment, but it seems like you can compile and use the software now, so that's great!

**Comment by poppop0911** [comment]
remove   ' --offsetStorage kafka'  param  
become normal

**Comment by taohorse** [comment]
if remove, can not monitor  kafka






At 2017-02-15 12:18:57, "poppop0911" <notifications@github.com> wrote:


remove ' --offsetStorage kafka' param
become normal

**Comment by chadlwm** [comment]
I rebuild one from source, the details in #111

**Comment by rcasey212** [comment]
@poppop0911 @taohorse @chadlwm This repo is defunct.  Use this repo instead: https://github.com/Morningstar/kafka-offset-monitor

You can then grab the latest compiled release and use that.
